// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qetghqlavqnfntgztbnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFldGdocWxhdnFuZm50Z3p0Ym5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzYzOTgsImV4cCI6MjA2MDUxMjM5OH0.XxyH3WlDJOYwjqj0rIPC0zYZS6WlaW-v5of8x6LQzBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);